# Close issues and pull requests
close: true

# Lock issues and pull requests
lock: true

pulls:
  comment: >
    This repository does not accept Pull Requests (PR) anymore.
    Development has moved to https://gitlab.alpinelinux.org/alpine/aports
    Please signup and create a Merge Request (MR) instead.
    Sorry for the inconvenience caused.
  lock: true

