---
kind: pipeline
name: v3.9-x86

clone:
  depth: 50

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:v3.9-x86
    commands:
      - linux32 build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: v3.9-x86_64

clone:
  depth: 50

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:v3.9-x86_64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: v3.9-aarch64

clone:
  depth: 50

platform:
  os: linux
  arch: arm64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:v3.9-aarch64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: v3.9-armhf

clone:
  depth: 50

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:v3.9-armhf
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: v3.9-armv7

clone:
  depth: 50

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: alpinelinux/alpine-drone-ci:v3.9-armv7
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
    pull: always

trigger:
  event:
    - pull_request

