sudo: required
dist: trusty
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=x86
    - ARCH=aarch64
    - ARCH=armhf
    - ARCH=ppc64le
before_install:
  - "wget 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.5.0/alpine-chroot-install' \
        && echo '1866bc078cab859cefcbdbbd2dee0141e0bee8d5  alpine-chroot-install' | sha1sum -c || exit 1"
  - alpine() { /alpine/enter-chroot -u "$USER" "$@"; }
install:
  - sudo sh alpine-chroot-install -a "$ARCH"
        -p 'build-base alpine-sdk libfetch-dev libressl libressl-dev linux-headers lua5.2-dev zlib-dev'
before_script:
  - /alpine/enter-chroot "addgroup $USER wheel && addgroup $USER abuild"
  - alpine abuild-keygen -ain
script:
  - alpine make
  - alpine src/apk --version
  - alpine make static
  - alpine src/apk.static --version
  - alpine make check
  - alpine make -C test root-tests
